language : node_js
node_js: '10'
os : linux
services: docker

before_install :
    - yarn install

script :
    - hexo generate
    - docker build -t shylockhg/blog .

# deploy to netlify.com automatically
deploy:
  - provider: script
    script: ./.travis-ci/deploy-docker.sh
    on:
        branch: master
    skip_cleanup: true
